[package]
name = "meilies-inspect"
version = "0.1.0"
authors = ["Clément Renault <renault.cle@gmail.com>"]
edition = "2018"

[dependencies]
futures = "0.1.26"
meilies = "0.2.0"
meilies-client = "0.2.0"
structopt = { version = "0.3.3", default-features = false }
tokio = "0.1.19"
